// Vince Petrelli All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace KitsuneGameplayTags
{
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_LiangYiPaste);
	//UI widget stack
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_ModalStack);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameMenu);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_HudStack);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_FrontendStack);

	//UI widgets
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_PressAnyKeyScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainMenuScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_OptionsScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_ConfirmScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainHudScreen);

	/** Input Tag*/
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Light);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Heavy);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Unequip);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hero_Jump);

	/*** `@BC`   描述: PlayerTag   `BC@` ***/
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Light);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Weapon_Heavy);

	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Weapon_Equip_Sword);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Weapon_Unequip_Sword);

	/*** `@BC`   描述: Shared 玩家敌人公用   `BC@` ***/
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

}

