// Vince Petrelli All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace KitsuneGameplayTags
{
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_LiangYiPaste);
	//UI widget stack
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_ModalStack);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_GameMenu);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_HudStack);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_WidgetStack_FrontendStack);

	//UI widgets
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_PressAnyKeyScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainMenuScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_OptionsScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_ConfirmScreen);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainHudScreen);

	/** Input Tag*/
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Light);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Heavy);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Unequip);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Hero_Jump);

	/*** `@BC`   描述: PlayerTag   `BC@` ***/
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sword_Equip);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sword_Unequip);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sword_Attack_Light);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Sword_Attack_Heavy);

	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Sword_Equip);
	KITSUNE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Sword_Unequip);

}

